### ISSUE TITLE
General Feature Discussion

### ISSUE THREAD

**Issue by fokoid** [thornecc/grouptodo#1]
In the absence of a slack channel, let's use this issue as a general discussion area for features etc.

**Comment by zuzana-kunckova** [comment]
## Phase one
### MVP
- [ ] basic functionality and UI (see issues #2 and #3)
  - [ ] display list of todos
  - [ ] add Todos
  - [ ] remove Todos
  - [ ] mark Todos as completed
  - [ ] mark Todos as cancelled
- [ ] storage
  - [ ] keep list of todos in IndexedDB
- [ ] design
  - [ ] prepare a high fidelity wireframe
  - [ ] implement the design with css/js

## Phase two
### Make the app into a PWA (connectivity independent, progressive, responsive)
- [ ] create the app shell
- [ ] set up service worker
- [ ] cache files in local storage

## Phase three
### Introduce authentication, allow users to log in
- [ ] OAuth (Google, Facebook, Twitter)
- [ ] Implement automated UI tests with Selenium

## Phase four
#### Allow multiple users to share/track todos within a group
- [ ] set up Firebase

---

Discussion on potential improvements welcome. Please comment below.

**Comment by fokoid** [comment]
Updated your list with checkboxes on items :) Also moved IndexedDB into MVP since it will be required to store the todo list at all.

**Comment by fokoid** [comment]
And what do you mean by _app shell_?

**Comment by zuzana-kunckova** [comment]
App shell or skeleton, the minimal html/css/js that is needed to be displayed on the screen, before the rest of the content is fetched and displayed.
https://developers.google.com/web/fundamentals/architecture/app-shell

**Comment by muyaszed** [comment]
Hi guys, I would like to implement Hot loading to this app which probably will help a bit on our development environment
