### ISSUE TITLE
Basic todo list functionality

### ISSUE THREAD

**Issue by fokoid** [thornecc/grouptodo#3]
- [x] array of todos
  - [x] add todo
  - [x] remove todo
  - [x] edit todo
  - [x] mark todo complete
- [ ] database of todos
  - [ ] preserve todo list state between sessions with IndexedDB

**Comment by fokoid** [comment]
Features now implemented in #6.

**Comment by zuzana-kunckova** [comment]
@thornecc , are you working on implementing IndexedDB and caching? If not, I could have a go.

**Comment by fokoid** [comment]
@zk433 Let's work on it together 👍
